Smart Wallets v2
fuseio/fuse-docs pull request #50
Opened 2023-12-06 09:02 UTC by emmaodia

2023-12-12 11:05 UTC, NikolayRn commented on api-references/fuse-smart-wallet-v-api.yaml
Please rename .yaml file to api-references/fuse-smart-wallet-v2-api.yaml, in current name version is missing

2023-12-12 11:06 UTC, NikolayRn commented on docs/smart-wallet-api-v/auth.api.mdx
version here

2023-12-12 11:06 UTC, NikolayRn requested changes
I see that in every file there is no version in its names, please add it

2023-12-12 20:58 UTC, emmaodia commented on api-references/fuse-smart-wallet-v-api.yaml
Thank you for the feedback @NikolayRn Done

2023-12-12 20:58 UTC, emmaodia commented on docs/smart-wallet-api-v/auth.api.mdx
Thank you for the feedback @NikolayRn Done

2023-12-13 13:59 UTC, NikolayRn approved these changes
LGTM

2023-12-13 14:18 UTC, merged